security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        user_doctrine:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: user_doctrine
            guard:
                authenticators:
                    - App\Security\Guard\WebAuthenticator
            logout:
                path: security_logout
    role_hierarchy:
        ROLE_CUSTOMER: ['ROLE_USER']
        ROLE_PRODUCER: ['ROLE_USER']
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
